services:
  db:
    image: mariadb:latest
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mariadb-admin ping -h localhost -u root -p$$MARIADB_ROOT_PASSWORD',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3032:3306
    networks:
      - notes
    volumes:
      - ./backend/db:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/1-init-db.sql
      - ./init-user.sql:/docker-entrypoint-initdb.d/2-init-user.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: prgms-notes-backend:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: prgms
      DB_PASSWORD: prgms
      DB_DATABASE: prgms_notes
      # 프론트엔드 컨테이너의 호스트 포트(3000)를 허용하도록 설정
      CORS_ALLOWED_ORIGIN: http://localhost:3000
    ports:
      - 3031:3031
    networks:
      - notes
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: prgms-notes-frontend:latest
    environment:
      VITE_API_BASE_URL: http://localhost:3031
    ports:
      - 3000:3000
    networks:
      - notes

networks:
  notes: {}
